version: "3.8"

volumes:
  postgres:
  bundle:
  node_modules:

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/app_development
      BUNDLE_PATH: /bundle
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b 0.0.0.0"
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - logux-proxy
    volumes:
      - ./app:/app
      - bundle:/bundle

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: app_development
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  logux-proxy:
    build:
      context: ./logux-proxy
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - LOGUX_BACKEND=http://app:3000/logux
      - LOGUX_CONTROL_PASSWORD=secret
    command: bash -c "yarn start"
    ports:
      - "31337:31337"
    volumes:
      - ./logux-proxy:/app:cached
      - node_modules:/app/node_modules
